name: Codacy Coverage
on: [push, pull_request]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - name: Set up Python
        uses: actions/setup-python@v6.2.0
        with:
          python-version: "3.13"
      - name: Install tox
        run: pip install tox
      - name: Generate coverage report
        run: tox -e coverage
      - name: Upload coverage to Codacy
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage.xml
